overrides:
  - files:
      - ".lintstagedrc.js"
      - "lint-staged.config.js"
    env:
      node: true
      es6: true
    extends:
      - eslint:recommended
      - plugin:import/errors
      - plugin:import/warnings
    parserOptions:
      ecmaVersion: 2018
      sourceType: script
  - files:
      - "**/tsconfig.*"
    rules:
      json/*:
        - error
        - allowComments: true
  - files:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.mjs"
    env:
      es6: true
    extends:
      - eslint:recommended
      - plugin:import/errors
      - plugin:import/warnings
    parserOptions:
      ecmaVersion: 2020
      sourceType: module
    rules:
      import/first: 1
      import/newline-after-import:
        - warn
        - count: 1
      import/no-cycle: 2
      import/no-extraneous-dependencies: 2
      import/no-self-import: 2
      import/no-unassigned-import: 1
      import/no-useless-path-segments:
        - error
        - noUselessIndex: true
      import/order:
        - warn
        - alphabetize:
            order: "asc"
          newlines-between: always
      import/no-webpack-loader-syntax: 2
      no-console: 1
      no-mixed-spaces-and-tabs:
        - error
        - smart-tabs
      no-namespace: 0
      no-process-env: 2
      sort-imports:
        - warn
        - ignoreDeclarationSort: true
  - files:
      - "**/*.json"
    extends:
      - plugin:json/recommended
  - files:
      - "**/*.md"
    extends:
      - "plugin:markdown/recommended"
    plugins:
      - "markdown"
    processor: "markdown/markdown"
  - files:
      - "**/*.ts"
      - "**/*.tsx"
    extends:
      - eslint:recommended
      - "plugin:@typescript-eslint/eslint-recommended"
      - "plugin:@typescript-eslint/recommended"
      - prettier
      - plugin:import/errors
      - plugin:import/typescript
      - plugin:import/warnings
    parser: "@typescript-eslint/parser"
    parserOptions:
      project:
        - "tsconfig.json"
    plugins:
      - "@typescript-eslint"
      - "import"
    settings:
      import/parsers:
        "@typescript-eslint/parser": [".ts", ".tsx"]
      import/resolver:
        typescript:
          alwaysTryTypes: true
          project:
            - "tsconfig.json"
            # - "tests/tsconfig.json"
    rules:
      "@typescript-eslint/explicit-function-return-type": 1
      "@typescript-eslint/no-floating-promises": 2
      "@typescript-eslint/no-misused-promises": 2
      "@typescript-eslint/promise-function-async": 2
      "@typescript-eslint/require-await": 2
      import/first: 1
      import/newline-after-import:
        - warn
        - count: 1
      import/no-cycle: 2
      import/no-extraneous-dependencies: 2
      import/no-self-import: 2
      import/no-unassigned-import: 1
      import/no-useless-path-segments:
        - error
        - noUselessIndex: true
      import/order:
        - warn
        - alphabetize:
            order: "asc"
          newlines-between: always
      import/no-webpack-loader-syntax: 2
      no-console: 1
      no-mixed-spaces-and-tabs:
        - error
        - smart-tabs
      no-namespace: 0
      no-process-env: 2
      require-await: 0 # required to be off by @typescript-eslint/require-await
      sort-imports:
        - warn
        - ignoreDeclarationSort: true
      # BANDAIDS BEYOND THIS POINT. REMOVE WHEN POSSIBLE.
  - files:
      - "**/test/*.ts"
      - "**/tests/*.ts"
      - "**/integration/*.ts"
      - "**/*.test.ts"
    env:
      mocha: true
      node: true
    rules:
      no-console: 0
  - files:
      - "**/*.yaml"
      - "**/*.yml"
      - ".lintstagedrc"
    plugins:
      - "yaml"
root: true
